language: node_js
node_js:
  - "8"
script:
  - npm install
  - npm run lint
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      sudo: required
      node_js: false
      before_install:
        - nvm install 8
        - rvm install 2.3
        - rvm install 2.3-dev
      install:
        - sudo apt-get install -y -qq inkscape
        - npm install
        - npm install coveralls
        - gem install fastlane
      android:
        components:
          - addon-google_apis-google-16
          - android-23
          - android-26
          - build-tools-23.0.1
          - build-tools-26.0.1
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - platform-tools
          - tools
      before_script:
        - ./utils/write_coveralls_config.sh
      script:
        - npm run lint
        - ./utils/run_build.sh
        - travis_wait 15 npm run coverage && cat ./coverage/lcov.info | npm run coveralls
      deploy:
        - provider: script
          skip_cleanup: true
          on:
            branch: master
          script: ./utils/run_deploy.sh beta
        - provider: script
          skip_cleanup: true
          on:
            tags: true
          script: ./utils/run_deploy.sh production
