language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
script:
  - npm install -g
  - npm run lint
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      sudo: required
      node_js: false
      before_install:
        - nvm install 8
      install:
        - sudo apt-get install -y -qq inkscape
        - npm install -g
        - npm install -g coveralls
      android:
        components:
          - addon-google_apis-google-16
          - android-23
          - android-26
          - build-tools-23.0.1
          - build-tools-26.0.1
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - platform-tools
          - tools
      before_script:
        - ./utils/write_coveralls_config.sh
      script:
        - npm run lint
        - ./utils/run_build.sh
        - travis_wait 15 npm run coverage && cat ./coverage/lcov.info | coveralls
    # - language: objective-c
    #   os: osx
    #   osx_image: xcode8.2
    #   node_js: false
    #   before_install:
    #     - nvm install 8
    #     - node --version
    #     - travis_retry npm install -g yarn
    #     - yarn -version
    #   install:
    #     - travis_retry gem install xcpretty
    #     - travis_retry yarn
    #   xcode_project: ios/DulceAppTemplate.xcodeproj
    #   xcode_scheme: ios/DulceAppTemplateTests
    #   script:
    #     - cd ios
    #     - xcodebuild -scheme DulceAppTemplate -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
    #     - travis_retry xctool run-tests -scheme DulceAppTemplate -sdk iphonesimulator -launch-timeout 90  ONLY_ACTIVE_ARCH=NO
